/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package container;

import controller.ContainerMenuFinanceiroController;
import javax.swing.JPanel;
import view.TelaCaixaFinanceiro;

/**
 *
 * @author Elyneker Luciani
 */
public class ContainerMenuFinanceiro extends javax.swing.JPanel {
    private final ContainerMenuFinanceiroController financeiroController;
    private TelaCaixaFinanceiro telaCaixaFinanceiro;

    /**
     * Creates new form ContainerMenuFinanceiro
     */
    public ContainerMenuFinanceiro() {
        initComponents();
        financeiroController = new ContainerMenuFinanceiroController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCaixa = new rsbuttom.RSButtonSub();
        jPanelCentro = new javax.swing.JPanel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCaixa.setForeground(new java.awt.Color(51, 51, 51));
        btnCaixa.setText("Caixa");
        btnCaixa.setColorTextHover(new java.awt.Color(51, 51, 51));
        btnCaixa.setColorTextNormal(new java.awt.Color(51, 51, 51));
        btnCaixa.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnCaixa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        jPanelCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCentro.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
            .addComponent(jPanelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        financeiroController.executa(evt);
    }//GEN-LAST:event_btnCaixaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonSub btnCaixa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCentro;
    // End of variables declaration//GEN-END:variables

    public JPanel getjPanelCentro() {
        return jPanelCentro;
    }

    public TelaCaixaFinanceiro getTelaCaixaFinanceiro() {
        return telaCaixaFinanceiro;
    }

    public void setTelaCaixaFinanceiro(TelaCaixaFinanceiro telaCaixaFinanceiro) {
        this.telaCaixaFinanceiro = telaCaixaFinanceiro;
    }

    
}
