/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package container;

import componentes.QuartoComponent;
import controller.QuartoController;
import java.awt.ComponentOrientation;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Elyneker Luciani
 */
public class ContainerQuarto extends javax.swing.JPanel {
    private QuartoController controllerQuarto = QuartoController.getInstancia();
    
    

    /**
     * Creates new form JPanelContainerQuarto
     */
    public ContainerQuarto() {
        initComponents();
        controllerQuarto.setQuartoController(this);
        this.jPanelCentro.setLayout(new GridLayout(6, 5, 5, 5));
        this.jPanelCentro.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
//        exibirQuartoComponente();
        controllerQuarto.exibirQuartoComponente();
        try {
            controllerQuarto.buscarStatusQuarto();
        } catch (SQLException ex) {
            Logger.getLogger(ContainerQuarto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ContainerQuarto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
   
    public QuartoController getControllerQuarto() {
        return controllerQuarto;
    }

    public void setControllerQuarto(QuartoController controllerQuarto) {
        this.controllerQuarto = controllerQuarto;
    }

    public JPanel getjPanelCentro() {
        return jPanelCentro;
    }

    public void setjPanelCentro(JPanel jPanelCentro) {
        this.jPanelCentro = jPanelCentro;
    }

    public JPanel getjPanelInferior() {
        return jPanelInferior;
    }

    public void setjPanelInferior(JPanel jPanelInferior) {
        this.jPanelInferior = jPanelInferior;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInferior = new javax.swing.JPanel();
        jPanelCentro = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(880, 479));

        jPanelInferior.setBackground(new java.awt.Color(204, 204, 255));
        jPanelInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanelCentroLayout = new javax.swing.GroupLayout(jPanelCentro);
        jPanelCentro.setLayout(jPanelCentroLayout);
        jPanelCentroLayout.setHorizontalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelCentroLayout.setVerticalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
            .addComponent(jPanelCentro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelInferior;
    // End of variables declaration//GEN-END:variables

   
}
