package container;

import controller.ContainerMenuClienteController;
import javax.swing.JPanel;
import view.TelaCadastroCliente;
import view.TelaPesquisaCliente;

/**
 *
 * @author Elyneker Luciani
 */
public class ContainerMenuCliente extends javax.swing.JPanel {
    private final ContainerMenuClienteController clienteController;
    private TelaCadastroCliente telaCadastroCliente;
    private TelaPesquisaCliente telaPesquisaCliente;
    

    /**
     * Creates new form ContainerMenuCliente
     */
    public ContainerMenuCliente() {
        initComponents();
        //clienteController.setMenuCliente(this);
        clienteController = new ContainerMenuClienteController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastrar = new rsbuttom.RSButtonSub();
        btnPesquisar = new rsbuttom.RSButtonSub();
        jPanelCentro = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(800, 479));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrar.setForeground(new java.awt.Color(51, 51, 51));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setColorTextHover(new java.awt.Color(51, 51, 51));
        btnCadastrar.setColorTextNormal(new java.awt.Color(51, 51, 51));
        btnCadastrar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        btnPesquisar.setForeground(new java.awt.Color(51, 51, 51));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setColorTextHover(new java.awt.Color(51, 51, 51));
        btnPesquisar.setColorTextNormal(new java.awt.Color(51, 51, 51));
        btnPesquisar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, -1));

        jPanelCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCentro.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
            .addComponent(jPanelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        clienteController.executa(evt);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        clienteController.executa(evt);
    }//GEN-LAST:event_btnPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonSub btnCadastrar;
    private rsbuttom.RSButtonSub btnPesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCentro;
    // End of variables declaration//GEN-END:variables

   
    public JPanel getjPanelCentro() {
        return jPanelCentro;
    }

    public void setjPanelCentro(JPanel jPanelCentro) {
        this.jPanelCentro = jPanelCentro;
    }

    public TelaCadastroCliente getTelaCadastroCliente() {
        return telaCadastroCliente;
    }

    public void setTelaCadastroCliente(TelaCadastroCliente telaCadastroCliente) {
        this.telaCadastroCliente = telaCadastroCliente;
    }

    public TelaPesquisaCliente getTelaPesquisaCliente() {
        return telaPesquisaCliente;
    }

    public void setTelaPesquisaCliente(TelaPesquisaCliente telaPesquisaCliente) {
        this.telaPesquisaCliente = telaPesquisaCliente;
    }
    
    

    
}
