/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package container;

import controller.ContainerMenuConfigurarController;
import javax.swing.JPanel;
import view.TelaCadastroProduto;
import view.TelaValoresQuartos;

/**
 *
 * @author Elyneker Luciani
 */
public class ContainerMenuConfigurar extends javax.swing.JPanel {
    private final ContainerMenuConfigurarController configurarController;
    private TelaCadastroProduto telaProduto;
    private TelaValoresQuartos valorQuarto;

    /**
     * Creates new form ContainerMenuConfigurar
     */
    public ContainerMenuConfigurar() {
        initComponents();
        configurarController = new ContainerMenuConfigurarController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastrarProduto = new rsbuttom.RSButtonSub();
        btnCatQuartos = new rsbuttom.RSButtonSub();
        jPanelCentro = new javax.swing.JPanel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrarProduto.setText("Cadastrar Produto");
        btnCadastrarProduto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        btnCatQuartos.setText("Valores Quarto");
        btnCatQuartos.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnCatQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatQuartosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCatQuartos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, -1));

        jPanelCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCentro.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
            .addComponent(jPanelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        configurarController.executa(evt);
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void btnCatQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatQuartosActionPerformed
        configurarController.executa(evt);
    }//GEN-LAST:event_btnCatQuartosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonSub btnCadastrarProduto;
    private rsbuttom.RSButtonSub btnCatQuartos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCentro;
    // End of variables declaration//GEN-END:variables

    public TelaCadastroProduto getTelaProduto() {
        return telaProduto;
    }

    public void setTelaProduto(TelaCadastroProduto telaProduto) {
        this.telaProduto = telaProduto;
    }

    public JPanel getjPanelCentro() {
        return jPanelCentro;
    }

    public TelaValoresQuartos getValorQuarto() {
        return valorQuarto;
    }

    public void setValorQuarto(TelaValoresQuartos valorQuarto) {
        this.valorQuarto = valorQuarto;
    }
    
    
}
