package container;

import controller.ContainerMenuHospedagemController;
import javax.swing.JPanel;
import view.TelaPesquisaHistorico;

/**
 *
 * @author Elyneker Luciani
 */
public class ContainerMenuHospedagem extends javax.swing.JPanel {

    private ContainerMenuHospedagemController hospedagemController;
    private TelaPesquisaHistorico telaPesquisaHistorico;

    /**
     * Creates new form ContainerMenu
     */
    public ContainerMenuHospedagem() {
        initComponents();
        hospedagemController = new ContainerMenuHospedagemController(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHistorico = new rsbuttom.RSButtonSub();
        jPanelCentro = new javax.swing.JPanel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHistorico.setForeground(new java.awt.Color(51, 51, 51));
        btnHistorico.setText("Histórico");
        btnHistorico.setColorTextHover(new java.awt.Color(51, 51, 51));
        btnHistorico.setColorTextNormal(new java.awt.Color(51, 51, 51));
        btnHistorico.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnHistorico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        jPanelCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCentro.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
            .addComponent(jPanelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        hospedagemController.executa(evt);
    }//GEN-LAST:event_btnHistoricoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonSub btnHistorico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCentro;
    // End of variables declaration//GEN-END:variables

    public JPanel getjPanelCentro() {
        return jPanelCentro;
    }

    public void setjPanelCentro(JPanel jPanelCentro) {
        this.jPanelCentro = jPanelCentro;
    }

    public TelaPesquisaHistorico getTelaPesquisaHistorico() {
        return telaPesquisaHistorico;
    }

    public void setTelaPesquisaHistorico(TelaPesquisaHistorico telaPesquisaHistorico) {
        this.telaPesquisaHistorico = telaPesquisaHistorico;
    }

}
