/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package container;

/**
 *
 * @author Elyneker Luciani
 */
public class ContainerMenuCliente extends javax.swing.JPanel {

    /**
     * Creates new form ContainerMenuCliente
     */
    public ContainerMenuCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSButtonSub1 = new rsbuttom.RSButtonSub();
        rSButtonSub2 = new rsbuttom.RSButtonSub();
        jPanel2 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(800, 479));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonSub1.setForeground(new java.awt.Color(51, 51, 51));
        rSButtonSub1.setText("Cadastrar");
        rSButtonSub1.setColorTextHover(new java.awt.Color(51, 51, 51));
        rSButtonSub1.setColorTextNormal(new java.awt.Color(51, 51, 51));
        rSButtonSub1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rSButtonSub1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(rSButtonSub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        rSButtonSub2.setForeground(new java.awt.Color(51, 51, 51));
        rSButtonSub2.setText("Pesquisar");
        rSButtonSub2.setColorTextHover(new java.awt.Color(51, 51, 51));
        rSButtonSub2.setColorTextNormal(new java.awt.Color(51, 51, 51));
        rSButtonSub2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rSButtonSub2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(rSButtonSub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rsbuttom.RSButtonSub rSButtonSub1;
    private rsbuttom.RSButtonSub rSButtonSub2;
    // End of variables declaration//GEN-END:variables
}
