package view;

import controller.ReservaController;
import javax.swing.JLabel;
import rsbuttom.RSButtonMetro;

/**
 *
 * @author Elyneker Luciani
 */
public class TelaDadosReserva extends javax.swing.JPanel {
    private final ReservaController reservaController = new ReservaController();
    
    private static int numeroQuarto;

    /**
     * Creates new form DadosReserva
     * @param numQuarto
     */
    public TelaDadosReserva(int numQuarto) {
        initComponents();
        this.reservaController.setTelaDadosReserva(this);
        this.jLabelInformacao.setText("Informação do Quarto: " + numQuarto);
        TelaDadosReserva.numeroQuarto = numQuarto;
        reservaController.buscarDadosDaReserva(numeroQuarto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInformacao = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnEncerrar = new rsbuttom.RSButtonMetro();
        jLabel2 = new javax.swing.JLabel();
        jLabelDiaEntrada = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelTotalDias = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelValorDiaria = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelInformacao.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelInformacao.setText("Informações do Quarto:");

        btnEncerrar.setText("Encerrar");
        btnEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Dia de Entrada:");

        jLabelDiaEntrada.setText("jLabel3");

        jLabel4.setText("Total de dias:");

        jLabelTotalDias.setText("jLabel5");

        jLabel1.setText("Valor da Diária: R$");

        jLabelValorDiaria.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInformacao)
                            .addComponent(btnEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelValorDiaria))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDiaEntrada))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(42, 42, 42)
                                    .addComponent(jLabelTotalDias))))
                        .addGap(0, 630, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInformacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelDiaEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelTotalDias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelValorDiaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                .addComponent(btnEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrarActionPerformed
        reservaController.executarReserva(evt);
    }//GEN-LAST:event_btnEncerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnEncerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDiaEntrada;
    private javax.swing.JLabel jLabelInformacao;
    private javax.swing.JLabel jLabelTotalDias;
    private javax.swing.JLabel jLabelValorDiaria;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public RSButtonMetro getBtnEncerrar() {
        return btnEncerrar;
    }

    public void setBtnEncerrar(RSButtonMetro btnEncerrar) {
        this.btnEncerrar = btnEncerrar;
    }

    public JLabel getjLabelDiaEntrada() {
        return jLabelDiaEntrada;
    }

    public void setjLabelDiaEntrada(JLabel jLabelDiaEntrada) {
        this.jLabelDiaEntrada = jLabelDiaEntrada;
    }

    public JLabel getjLabelTotalDias() {
        return jLabelTotalDias;
    }

    public void setjLabelTotalDias(JLabel jLabelTotalDias) {
        this.jLabelTotalDias = jLabelTotalDias;
    }

    public static int getNumeroQuarto() {
        return numeroQuarto;
    }


    
    

    
}
