package view;

import com.toedter.calendar.JDateChooser;
import controller.PrincipalController;
import controller.QuartoController;
import controller.ReservaController;
import java.time.Instant;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Elyneker Luciani
 */
public class TelaReservaQuarto extends javax.swing.JPanel {

    //Esta instância permite ter acesso ao método para voltar a tela inicial
    private final PrincipalController principal = PrincipalController.getInstancia();
    private final QuartoController controllerQuarto;
    private ReservaController reservaController = new ReservaController();

    private static int idCategoriaDoQuarto;
    private static int numeroQuarto;
    private static int idQuarto;

    /**
     * Creates new form CadastroRapido
     *
     * @param idQuarto
     * @param numQuarto
     * @param idCategoria
     */
    public TelaReservaQuarto(int idQuarto, int numQuarto, int idCategoria) {
        initComponents();
        controllerQuarto = new QuartoController();
        controllerQuarto.setTelaInformacao(this);
        reservaController.setTelaInformacao(this);
        TelaReservaQuarto.idCategoriaDoQuarto = idCategoria;
        TelaReservaQuarto.numeroQuarto = numQuarto;
        TelaReservaQuarto.idQuarto = idQuarto;

        this.jLabelNumeroQuarto.setText("Reserva no Quarto Número: " + numeroQuarto);
        //Informa o nome da categoria do quarto, buscando pelo id da categoria
        this.jLabelCategoriaQuarto.setText("Categoria deste quarto: " + controllerQuarto.buscarCategoriaQuarto(idCategoriaDoQuarto));
        controllerQuarto.buscarQuantidadePessoaPorQuarto(idCategoriaDoQuarto);
        this.jCalendarPrevisaoSaida.setMinSelectableDate(Date.from(Instant.now()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelNumeroQuarto = new javax.swing.JLabel();
        jLabelCategoriaQuarto = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableResultadoPesquisa = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabelNomeCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxQntPessoa = new javax.swing.JComboBox<>();
        jCalendarPrevisaoSaida = new com.toedter.calendar.JDateChooser();
        btnHospedar = new rsbuttom.RSButtonSub();
        btnCancelar = new rsbuttom.RSButtonSub();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNumeroQuarto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelNumeroQuarto.setText("quarto numero");

        jLabelCategoriaQuarto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelCategoriaQuarto.setText("Categoria deste Quarto:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel6.setText("Hospedar Cliente");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setText("Informe o nome do cliente ou o número do documento e pressione a tecla ENTER:");

        jTextFieldPesquisar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
        });

        jTableResultadoPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Documento", "Celular"
            }
        ));
        jTableResultadoPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableResultadoPesquisaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableResultadoPesquisa);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Voê está hospedando o cliente:");

        jLabelNomeCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelNomeCliente.setForeground(new java.awt.Color(204, 0, 0));
        jLabelNomeCliente.setText("Nome do Cliente");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Informe a previsão de saída do cliente:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Informe a quantidade de pessoas:");

        jComboBoxQntPessoa.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jCalendarPrevisaoSaida.setDateFormatString("dd-MM-yyyy");
        jCalendarPrevisaoSaida.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        btnHospedar.setText("Hospedar");
        btnHospedar.setColorHover(new java.awt.Color(0, 153, 255));
        btnHospedar.setColorNormal(new java.awt.Color(240, 240, 240));
        btnHospedar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnHospedar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospedarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setColorHover(new java.awt.Color(0, 153, 255));
        btnCancelar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelNumeroQuarto)
                                .addGap(68, 68, 68)
                                .addComponent(jLabelCategoriaQuarto))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelNomeCliente))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCalendarPrevisaoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jComboBoxQntPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnHospedar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(193, 193, 193))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategoriaQuarto)
                    .addComponent(jLabelNumeroQuarto))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelNomeCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendarPrevisaoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxQntPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHospedar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        principal.executa(evt);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnHospedarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospedarActionPerformed
        reservaController.executarReserva(evt);
    }//GEN-LAST:event_btnHospedarActionPerformed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed
        reservaController.executarKeyEvent(evt);
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed

    private void jTableResultadoPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableResultadoPesquisaMouseClicked
        reservaController.executaMouseClicked(evt);
    }//GEN-LAST:event_jTableResultadoPesquisaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonSub btnCancelar;
    private rsbuttom.RSButtonSub btnHospedar;
    private com.toedter.calendar.JDateChooser jCalendarPrevisaoSaida;
    private javax.swing.JComboBox<Object> jComboBoxQntPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCategoriaQuarto;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelNumeroQuarto;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableResultadoPesquisa;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables

    public JComboBox<Object> getjComboBoxQntPessoa() {
        return jComboBoxQntPessoa;
    }

    public void setjComboBoxQntPessoa(JComboBox<Object> jComboBoxQntPessoa) {
        this.jComboBoxQntPessoa = jComboBoxQntPessoa;
    }

    public void setReservaController(ReservaController reservaController) {
        this.reservaController = reservaController;
    }

    public JDateChooser getjCalendarPrevisaoSaida() {
        return jCalendarPrevisaoSaida;
    }

    public static int getNumeroQuarto() {
        return numeroQuarto;
    }

    public static int getIdQuarto() {
        return idQuarto;
    }

    public JTable getjTableResultadoPesquisa() {
        return jTableResultadoPesquisa;
    }

    public void setjTableResultadoPesquisa(JTable jTableResultadoPesquisa) {
        this.jTableResultadoPesquisa = jTableResultadoPesquisa;
    }

    public JTextField getjTextFieldPesquisar() {
        return jTextFieldPesquisar;
    }

    public JLabel getjLabelNomeCliente() {
        return jLabelNomeCliente;
    }

}
